# Generated by Django 4.2.2 on 2023-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("image", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("desc", models.TextField()),
                ("author_name", models.CharField(max_length=300)),
                ("author_image", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Catg_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.TextField()),
                ("image", models.ImageField(upload_to="media")),
                ("caption", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=500)),
                ("Description", models.TextField()),
                ("picture", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Vid_cont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Vid_news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.TextField()),
                ("image", models.ImageField(upload_to="media")),
                ("caption", models.CharField(max_length=100)),
                ("desc", models.TextField()),
            ],
        ),
    ]
