# Generated by Django 4.2.2 on 2023-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vid_cont",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vid_news",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
