# Generated by Django 4.2.2 on 2023-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="First_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("category", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("author_name", models.CharField(max_length=300)),
                ("author_image", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(upload_to="pictures"),
        ),
    ]
