# Generated by Django 4.2.2 on 2023-07-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_first_page_alter_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=500)),
                ("comment", models.TextField()),
                ("rank", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("heading", models.TextField()),
                ("image", models.ImageField(upload_to="media")),
                ("desc", models.TextField()),
                ("long_desc", models.TextField()),
                ("author_name", models.CharField(blank=True, max_length=300)),
                ("author_image", models.ImageField(blank=True, upload_to="media")),
                (
                    "labels",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "default"),
                            ("trending", "trending"),
                            ("videos", "videos"),
                            ("cat", "cat"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Catg_News",
        ),
        migrations.DeleteModel(
            name="First_page",
        ),
        migrations.DeleteModel(
            name="Vid_news",
        ),
        migrations.RemoveField(
            model_name="category",
            name="author_image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name="vid_cont",
            name="caption",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="vid_cont",
            name="full_desc",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vid_cont",
            name="heading",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="desc",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.category"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.comment"
            ),
        ),
    ]
