# Generated by Django 4.2.2 on 2023-07-05 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_comment_news_delete_catg_news_delete_first_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="comment",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
