# Generated by Django 4.2.2 on 2023-07-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_news_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
