# Generated by Django 4.2.2 on 2023-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_news_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vid_cont",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
