# Generated by Django 4.2.2 on 2023-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_remove_news_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=500)),
                ("password", models.CharField(max_length=500)),
            ],
        ),
    ]
