# Generated by Django 4.2.2 on 2023-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=300)),
                ("number", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
    ]
