# Generated by Django 4.2.2 on 2023-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0013_rename_name_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="vid_cont",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
