# Generated by Django 4.2.2 on 2023-07-15 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0014_vid_cont_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vid_cont",
            name="rank",
        ),
    ]
