# Generated by Django 4.2.2 on 2023-07-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0015_remove_vid_cont_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="vid_cont",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vid_cont",
            name="desc",
            field=models.TextField(blank=True),
        ),
    ]
